aws cloudformation list-stacks \
--profile mfa \
--stack-status-filter \
CREATE_IN_PROGRESS \
CREATE_COMPLETE \
ROLLBACK_IN_PROGRESS \
ROLLBACK_FAILED \
ROLLBACK_COMPLETE \
DELETE_IN_PROGRESS \
DELETE_FAILED \
UPDATE_IN_PROGRESS \
UPDATE_COMPLETE_CLEANUP_IN_PROGRESS \
UPDATE_COMPLETE \
UPDATE_ROLLBACK_IN_PROGRESS \
UPDATE_ROLLBACK_FAILED \
UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS \
UPDATE_ROLLBACK_COMPLETE REVIEW_IN_PROGRESS \
--output table \
--query 'StackSummaries[*].[StackName,StackStatus]'
